### PR TITLE
Updated devsprint information in FAQs

### PR DESCRIPTION
**Pull request by Sc0rpi0n101**

### CODE REVIEW

**Comment by palnabarun** [comment]
@Sc0rpi0n101 -- can you please change your editor line ending to use `LF` instead of `CRLF`?

**Comment by Sc0rpi0n101** [comment]
> @Sc0rpi0n101 -- can you please change your editor line ending to use `LF` instead of `CRLF`?

But I did change it to LF for this PR. 
image

**Comment by SaptakS** [comment]
@Sc0rpi0n101 can you please resolve the merge conflicts?

**Comment by palnabarun** [comment]
Changed base branch to `main` from `master`.

**Comment by Sc0rpi0n101** [comment]
I'm going to reopen this with some more changes

**Pull request closed without merging**
