### PR TITLE
update talk schedule

### PR DESCRIPTION
**Pull request by RiteshAgrawal**

### CODE REVIEW

**Review by sayanchowdhury — APPROVED** [review]

**Comment by palnabarun** [comment]
Splitting a slot into two breaks the schedule. Currently, the code can't handle it.

image

@SaptakS -- thoughts, please. This is a new thing. :fearful:

**Review by SaptakS — COMMENTED** [review]
Since we don't have a duration logic (I was of the impression all talks will be of the same duration so didn't add that into complexity, hence the height of talks aren't fixed), I am thinking of changing the data structure a bit such that at root level, it will have a talk with no title and `split: True`. And then have `talks:...` which will contain the details for the two talks (title and speaker names). That way I can loop through the talks in that split session.

**Review by sayanchowdhury — CHANGES_REQUESTED** [review]
I talked with Saptak about this.

**Comment by SaptakS** [comment]
> Since we don't have a duration logic (I was of the impression all talks will be of the same duration so didn't add that into complexity, hence the height of talks aren't fixed), I am thinking of changing the data structure a bit such that at root level, it will have a talk with no title and `split: True`. And then have `talks:...` which will contain the details for the two talks (title and speaker names). That way I can loop through the talks in that split session.

As soon as I started implementing this, I realized it will become a disaster for the mobile version, also wouldn't have a good way of showing the start time of the second session in the split session.

So I went with a much more hard coded solution. Technically I could have made it less hard coded by adding few keys to the sessions in that particular date and time, and used that key to assign the CSS. But I feel given that this is a single specific item, checking by the data, time and duration suffices.

If anyone feels strongly about using another key to check and assign CSS, let me know.

Also, if anyone argues, that one can easily use JS to check and adjust the CSS, valid point, but we have very minimal JS in the entire website, and I would prefer to keep it that way.

**Review by palnabarun — APPROVED** [review]

**Comment by palnabarun** [comment]
Closed this and opened #149 with the same changes since I can't merge with the blocking review.

**Pull request closed without merging**
