### PR TITLE
Bug fix refresh favicon #24

### PR DESCRIPTION
**Pull request by singhalshubham89**
Added new design logo as Favicon, please check the below image
image
Please note:- this is my first minor contribution to open source, any suggestion is welcome

### CODE REVIEW

**Review by palnabarun — APPROVED** [review]
LGTM!

Putting in a lazy consensus until Friday 07 August 10PM for merge.

**Comment by palnabarun** [comment]
@singhalshubham89 Before merging, can you please squash all your commits and clean up your commit history?

**Comment by singhalshubham89** [comment]
@palnabarun Done, please check if it it's okay now

**Comment by singhalshubham89** [comment]
@palnabarun , please check now and thanks a lot for suggestion

**Comment by palnabarun** [comment]
Thank you @singhalshubham89 :)

PS: Please read https://chris.beams.io/posts/git-commit/ on how to write a good message. This time I am modifying the commit message manually.

**Comment by singhalshubham89** [comment]
> Thank you @singhalshubham89 :)
> 
> PS: Please read https://chris.beams.io/posts/git-commit/ on how to write a good message. This time I am modifying the commit message manually.

Sure. I will make sure of writing good messages in future commits

**Pull request merged**
