### PR TITLE
PyQt spell fix

### PR DESCRIPTION
**Pull request by anistark**

### CODE REVIEW

**Review by palnabarun — APPROVED** [review]
@anistark -- Can you ask the speaker as well to update the title on Junction?

**Comment by anistark** [comment]
> @anistark -- Can you ask the speaker as well to update the title on Junction?

@RiteshAgrawal ^^

**Comment by palnabarun** [comment]
@RiteshAgrawal Any progress on this? I see that the proposal still has the wrong terminology.

**Comment by RiteshAgrawal** [comment]
@palnabarun just sent the mail to speaker.

**Comment by SaptakS** [comment]
Seems the speaker has at least fixed the spelling in their title, though it's messed in some other places. Still merging this as this PR solves the issue related to this repo (i.e. fixing spelling in the website)

**Pull request merged**
