### PR TITLE
[MINOR] Adding logo to navbar

### PR DESCRIPTION
**Pull request by navinpai**
Fix for #21 

Screenshot 2020-07-13 at 1 50 37 PM

### CODE REVIEW

**Comment by Sc0rpi0n101** [comment]
From your image, that logo looks a little too large. maybe make it a tiny bit smaller.

**Comment by ananyo2012** [comment]
@navinpai Can you make it bit more towars left and make the transition faster ? Also the logo needs to be there always in the non-home pages.

**Comment by palnabarun** [comment]
Just being the devil's advocate here, doesn't it look odd a bit?

Two concerns:
1. When I am at the top of the page, there is no logo on the navbar. When I scroll down, the logo pans in from the left. This results in inconsistent behavior.
2. Putting Logo in the navbar which is centered throws symmetry out of context.

**Comment by ananyo2012** [comment]
> Just being the devil's advocate here, doesn't it look odd a bit?
> 
> Two concerns:
> 
> 1. When I am at the top of the page, there is no logo on the navbar. When I scroll down, the logo pans in from the left. This results in inconsistent behavior.

That's what I mentioned in my previous comment, we need to tweak the transition. Also the logo will be always present for non-home pages
> 2. Putting Logo in the navbar which is centered throws symmetry out of context.

The logo has to be placed further left. I think this is what you meant ?

**Comment by palnabarun** [comment]
Changed base branch to `main` from `master`.

**Comment by SaptakS** [comment]
@navinpai can you take a look at the merge conflicts?

**Comment by palnabarun** [comment]
Closing due to inactivity.

**Pull request closed without merging**
