### PR TITLE
Website styling changes

### PR DESCRIPTION
**Pull request by Sc0rpi0n101**
* Updated the .content styles
* Added a title element for website content
* Moved the coc page and about page inside coc and about folders
* Moved the favicon to assets
* Updated the links to some assets to make them relative

### CODE REVIEW

**Comment by Sc0rpi0n101** [comment]
I'm not sure who handles the design team now, so tagging @sayanchowdhury @palnabarun

**Comment by Sc0rpi0n101** [comment]
ping @palnabarun

**Comment by palnabarun** [comment]
@Sc0rpi0n101 -- since https://github.com/pythonindia/inpycon2020/pull/50 merged, you can drop the second commit from this PR.

**Comment by Sc0rpi0n101** [comment]
Alright

**Comment by palnabarun** [comment]
@Sc0rpi0n101 -- any updates on this?

**Comment by Sc0rpi0n101** [comment]
I'll update this tomorrow. I have some work today.

**Comment by palnabarun** [comment]
Changed base branch to `main` from `master`.

**Comment by SaptakS** [comment]
@Sc0rpi0n101 can you take a look at the merge conflicts?

**Comment by Sc0rpi0n101** [comment]
> @Sc0rpi0n101 can you take a look at the merge conflicts?

Sure, I'll update it.

**Comment by Sc0rpi0n101** [comment]
This has been stale for too long. I'm not sure if this is required anymore. 
I'll try to open another one after seeing if the changes would be useful.

**Pull request closed without merging**
