### PR TITLE
Correct Code of Conduct link

### PR DESCRIPTION
**Pull request by ju-sh**
Correct code of conduct link in Readme

### CODE REVIEW

**Comment by ju-sh** [comment]
Not sure if it belongs here, but the code of conduct link in the townscript page for booking tickets to PyCon India 2020 points to CoC for PyCon India 2019.

pyconin2020

**Comment by vipulgupta2048** [comment]
@inovizz Can you please check this out :up:

**Review by palnabarun — APPROVED** [review]

**Comment by palnabarun** [comment]
@ju-sh Thank you for your contribution. :smile: 

Can you please squash your commits?

**Comment by ju-sh** [comment]
@palnabarun I've combined the commits.

**Comment by palnabarun** [comment]
@ju-sh -- Thank you again! :slightly_smiling_face:

**Pull request merged**
